name: CI Unittest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Set up Python 3.12.0
      uses: actions/setup-python@v3
      with:
        python-version: "3.12.0"
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Install ngrok
      run: |
        wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
        unzip ngrok-stable-linux-amd64.zip
        chmod +x ngrok
        mv ngrok /usr/local/bin/ngrok
 
    - name: Start ngrok
      run: |
        ./ngrok http 5000 -host-header="localhost:5000" &
        echo "Ngrok is starting..."
        sleep 10  # Give ngrok some time to initialize
        background: true
      
    - name: Start API server
      run: |
        python Backend/server.py & 
        sleep 10 

    - name: Test with unittest
      run: |
        python test/test_backend.py

    - name: Upload test artifacts
      uses: actions/upload-artifact@v3 
      with:
        name: test_report
        path: artifacts/
